sudo: required
services:
  - docker

script:
  - docker build -t homie-controller:build -f Dockerfile.build .
  - docker run homie-controller:build /usr/local/bin/get-artifact > homie-controller
  - docker build -t homie-controller:runtime .

