FROM jbonachera/arch

ENV GOPATH /usr/local/src/go
RUN pacman -S --noconfirm go git
RUN mkdir -p $GOPATH/src/github.com/jbonachera
WORKDIR $GOPATH/src/github.com/jbonachera/homie-controller
CMD go get ./... && go test ./... && go build -o release/homie-controller
